//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserAuthAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public string firstName { get; set; }
        public string middleName { get; set; }
        public string lastName { get; set; }
        public string contact { get; set; }
    
        public virtual User User { get; set; }
    }
}
